name: Client
on:
  push:
    branches-ignore:
      - master
    paths:
      - 'build/ui/*'
  pull_request:
    branches-ignore:
      - master
    paths:
      - 'build/ui/*'
jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - uses: actions/checkout@v2
      - uses: c-hive/gha-npm-cache@v1.0.2
      - name: Install dependencies
        run: npm ci
      - name: Build Vue.js App
        run: npm run client:build
  lint:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - uses: actions/checkout@v2
      - uses: c-hive/gha-npm-cache@v1.0.2
      - name: Install dependencies
        run: npm ci
      - name: Run eslint
        run: npm run client:lint
