name: Deploy CI
on:
  release:
    types: [created]
  pull_request_target:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
jobs:
  vercel:
    name: Vercel
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: c-hive/gha-npm-cache@v1
      - name: Install dependencies
        run: npm ci
      - name: Build files
        run: npm run build
      - name: Deploy to Vercel Action
        uses: BetaHuhn/deploy-to-vercel-action@v1.3.3
        with:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          ALIAS_DOMAINS: |
            qrgen.cc
          PR_PREVIEW_DOMAIN: "{REPO}-{PR}.betahuhn.vercel.app"
